--- #Copying Multiple RPM to the Destination Server and Install using via Yum
- hosts: CENTOS
  remote_user: ansible
  sudo: yes
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Copy multiple files in Ansible with different permissions
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{item.mode}}"
    with_items:
      - { src: '/home/paul/gc-7.2d-7.el7.x86_64.rpm',dest: '/tmp/', mode: '0644'}
      - { src: '/home/paul/perl-NKF-2.1.3-5.el7.x86_64.rpm',dest: '/tmp/', mode: '0644'}
      - { src: '/home/paul/w3m-0.5.3-36.git20180125.el7.x86_64.rpm',dest: '/tmp/', mode: '0644'}

####Update the with_items with the { src: '/home/paul/w3m-0.5.3-36.git20180125.el7.x86_64.rpm',dest: '/tmp/', mode: '0575'} as needed

  - name: find rpm files and register the result 
    find:
      paths: /tmp/
      patterns: "*.rpm"
    register: rpm_files

# Create a list of the rpms to use with the yum install command
  - set_fact:
      rpm_list: "{{ rpm_files.files | map(attribute='path') | list}}"

# Use yum to install with a list
  - name: install rpm files using rpm_list
    yum:
      name: "{{rpm_list}}"
      state: present

# Running the command and copying the output to driver-status.txt
#  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
#    file:
#      path: /root/test/{{ inventory_hostname }}-raid-driver-output.txt
#      state: touch
#     mode: u+rw,g-wx,o-rwx
#      modification_time: preserve
#      access_time: preserve
# Running the Raid  and copying the output to driver-status.txt file
  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    raw: uptime >> /root/test/shakeelj2c.mylabserver.com-raid-driver-output.txt
