---
- hosts: CENTOS
  remote_user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no

  vars:
  - dnsname: "{{ inventory_hostname }}"
  - tmppath: "/root/test/"
  - crtpath: "{{ tmppath }}{{ dnsname }}.crt"
  - pempath: "{{ tmppath }}{{ dnsname }}.pem"
  - csrpath: "{{ tmppath }}{{ dnsname }}.csr"
  - pfxpath: "{{ tmppath }}{{ dnsname }}.pfx"
  - private_key_password: "password123"
  tasks:
  - name: Ensure python OpenSSL dependencies are installed.
    pip:
      name: pyOpenSSL
      state: present  


  - file:
      path: "{{ tmppath }}"
      state: absent

  - file:
      path: "{{ tmppath }}"
      state: directory

  - name: "Generate the private key file to sign the CSR"
    openssl_privatekey:
      path: "{{ pempath }}"
      passphrase: "{{ private_key_password }}"
      cipher: aes256

  - name: Set Private Key Permissions 
    file:
      path: '{{ pempath }}'
      state: 'file'
      owner: shakeel
      group: shakeel
      mode: 0666

  - name: "Generate the CSR file signed with the private key"
    openssl_csr:
      path: "{{ csrpath }}"
      privatekey_path: "{{ pempath }}"
      privatekey_passphrase: "{{ private_key_password }}"
      common_name: "{{ dnsname }}"
      country_name: 'US'
      state_or_province_name: 'Virgina'
      locality_name: 'Dulles'
      organization_name: 'Raytheon'
      organizational_unit_name: 'Caracal'
      email_address: 'support@raytheon.com'
      subject_alt_name: 'DNS: {{ inventory_hostname }}'      

 
  - name: "Sign the CSR file as a CA to turn it into a certificate"
    openssl_certificate:
      path: "{{ crtpath }}"
      privatekey_path: "{{ pempath }}"
      privatekey_passphrase: "{{ private_key_password }}"
      csr_path: "{{ csrpath }}"
      provider: selfsigned


  - name: "Convert the signed certificate into a PKCS12 file with the attached private key"
    openssl_pkcs12:
      action: export
      path: "{{ pfxpath }}"
      name: "{{ dnsname }}"
      privatekey_path: "{{ pempath }}"
      privatekey_passphrase: "{{ private_key_password }}"
      passphrase: password
      certificate_path: "{{ crtpath }}"
      state: present

  


